### ISSUE TITLE
Checking for trailing expressions in `cond`

### ISSUE THREAD

**Issue by abhillman** [Bogdanp/racket-review#12]
This could be quite handy; i.e.

```racket
(define (do-thing) 123)
(cond [...] (do-thing) (error "bla bla))
```

... where there is a warning here about not having an `else` clause. Currently, a warning about `else` clauses is only raised if there are no trailing expressions.

**Comment by abhillman** [comment]
Related: https://github.com/Bogdanp/racket-review/issues/13

**Comment by Bogdanp** [comment]
We can check for square brackets and we already check for else clauses in `cond`:

```
$ cat test.rkt
#lang racket/base

(cond
  [1 2])
$ raco review test.rkt
test.rkt:3:1:warning:this cond expression does not have an else clause
```

But we can't check for clauses like in your example, because they could be valid. For example:

```
$ cat test.rkt
#lang racket/base

(define thing "hi")
(displayln
 (cond
   [thing]))
$ racket test.rkt
hi
```
