### ISSUE TITLE
extensibility?

### ISSUE THREAD

**Issue by jbclements** [Bogdanp/racket-review#2]
Is this linter designed in a way that would make it moderately easy to extend? If so, have you considered writing a short guide for that? A ten-second look through the code suggests that you do have a notion of different kinds of patterns, so I'm guessing it might not be too hard.

**Comment by Bogdanp** [comment]
It depends on what you mean by "extensible". It's easy to modify the code and add new/missing patterns, but it's not currently possible for another package to hook its own patterns into the linter. I think the latter could be done, but I'd be curios to know what kinds of extensions you'd want to add or even if that's the kind of extensibility you had in mind.

**Comment by Bogdanp** [comment]
It's now (finally!) possible for other packages to extend the set of linting rules supported by this package: https://github.com/Bogdanp/racket-review?tab=readme-ov-file#adding-custom-rules

If there's interest, I'll write more extensive docs.
