### ISSUE TITLE
Identifiers containing ~ are mishandled

### ISSUE THREAD

**Issue by aymanosman** [Bogdanp/racket-review#8]
Here is an example which demonstrates the bug.

```sh
$ echo > example.rkt '
quote> #lang racket
quote>
quote> (provide ~foo)
quote>
quote> (define (~foo) 42)
quote> '
$ raco review example.rkt
/tmp/review-bug/example.rkt:6:10:warning:identifier '~~foo' is never used
/tmp/review-bug/example.rkt:4:10:error:identifier '~foo' provided but not defined
```

Another example:

<img width="1015" alt="Screen Shot 2020-10-17 at 13 36 31" src="https://user-images.githubusercontent.com/3605049/96337280-d545a600-107d-11eb-8556-a9b816159213.png">

**Comment by Bogdanp** [comment]
Thanks! This should now be fixed.
